### PR TITLE
Add end to end encrypted server and client.

### PR DESCRIPTION
**Pull request by Sussy-OS**
Add an example program I made. :)

### CODE REVIEW

**Comment by mas6y6** [comment]
Accepted

**Comment by mas6y6** [comment]
Please readd your sb3 file

**Comment by Sussy-OS** [comment]
Thanks!

**Comment by mas6y6** [comment]
Np

**Comment by mas6y6** [comment]
I have not been working on this because I am busy working on something else

**Comment by mas6y6** [comment]
Next time please add them to a folder please

**Comment by Sussy-OS** [comment]
> I have not been working on this because I am busy working on something else

Yeah, ofc.

> Next time please add to a folder please

Sure.

**Comment by Sussy-OS** [comment]
Could you add credits to my example as well, please?

**Comment by mas6y6** [comment]
Sure

**Pull request merged**
